@startuml
skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
    RoundCorner 20
}

left to right direction

class MemoryBlock {
    + Data: int
    + Header: int
    + Free: Boolean
    + MemoryAddress: int
}

MemoryBlockC : "Data: 16 bytes"
MemoryBlockC : "Header: 8 bytes"
MemoryBlockC : "Free: No"
MemoryBlockC : "MemoryAddress: 0x00000048"
MemoryBlockC --> MemoryBlockB : Return Link

MemoryBlockB : "Data: 24 bytes"
MemoryBlockB : "Header: 8 bytes"
MemoryBlockB : "Free: No"
MemoryBlockB : "MemoryAddress: 0x00000028"
MemoryBlockB --> MemoryBlockA : Return Link

MemoryBlockA : "Data: 32 bytes"
MemoryBlockA : "Header: 8 bytes"
MemoryBlockA : "Free: Yes"
MemoryBlockA : "MemoryAddress: 0x00000000"
MemoryBlockA --> Null

@enduml